build neurodesk and vnm images

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -25,27 +25,10 @@ jobs:
     - uses: actions/setup-python@v2
       with:
         python-version: 3.8
-    - name: Pull latest build from Github Packages
+    - name: login to docker hubs
       run: |
         echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
         echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
-        IMAGEID=docker.pkg.github.com/$GITHUB_REPOSITORY/neurodesk
-        IMAGEID=$(echo $IMAGEID | tr '[A-Z]' '[a-z]')
-        {
-          docker pull $IMAGEID \
-            && ROOTFS_CACHE=$(docker inspect --format='{{.RootFS}}' $IMAGEID) \
-            && echo "ROOTFS_CACHE=$ROOTFS_CACHE" >> $GITHUB_ENV
-        } || echo "$IMAGEID not found. Resuming build..."
-        echo "IMAGEID=$IMAGEID" >> $GITHUB_ENV
-    - name: Build new image
-      run: |
-        SHORT_SHA=$(git rev-parse --short $GITHUB_SHA)
-        docker build . --file Dockerfile --tag $IMAGEID:$SHORT_SHA --cache-from $IMAGEID --label "GITHUB_REPOSITORY=$GITHUB_REPOSITORY" --label "GITHUB_SHA=$GITHUB_SHA"
-        ROOTFS_NEW=$(docker inspect --format='{{.RootFS}}' $IMAGEID:$SHORT_SHA)
-        BUILDDATE=`date +%Y%m%d`
-        echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
-        echo "ROOTFS_NEW=$ROOTFS_NEW" >> $GITHUB_ENV
-        echo "BUILDDATE=$BUILDDATE" >> $GITHUB_ENV
     - name: Test neurodesk cli version
       run: |
         #setup singularity 2.6.1 from neurodebian
@@ -54,10 +37,26 @@ jobs:
         sudo apt-get update
         sudo apt-get install singularity-container 
         /bin/bash .github/workflows/test_neurodesk_cli.sh
-    - name: Test container
+    - name: Pull latest neurodesk build from Github Packages
       run: |
-        /bin/bash .github/workflows/test_neurodesk_image.sh
-    - name: Push to Github packages (if changes found)
+        IMAGEID=docker.pkg.github.com/$GITHUB_REPOSITORY/neurodesk
+        IMAGEID=$(echo $IMAGEID | tr '[A-Z]' '[a-z]')
+        {
+          docker pull $IMAGEID \
+            && ROOTFS_CACHE=$(docker inspect --format='{{.RootFS}}' $IMAGEID) \
+            && echo "ROOTFS_CACHE=$ROOTFS_CACHE" >> $GITHUB_ENV
+        } || echo "$IMAGEID not found. Resuming build..."
+        echo "IMAGEID=$IMAGEID" >> $GITHUB_ENV
+    - name: Build new neurodesk image
+      run: |
+        SHORT_SHA=$(git rev-parse --short $GITHUB_SHA)
+        docker build . --file neurodesk/Dockerfile --tag $IMAGEID:$SHORT_SHA --cache-from $IMAGEID --label "GITHUB_REPOSITORY=$GITHUB_REPOSITORY" --label "GITHUB_SHA=$GITHUB_SHA"
+        ROOTFS_NEW=$(docker inspect --format='{{.RootFS}}' $IMAGEID:$SHORT_SHA)
+        BUILDDATE=`date +%Y%m%d`
+        echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
+        echo "ROOTFS_NEW=$ROOTFS_NEW" >> $GITHUB_ENV
+        echo "BUILDDATE=$BUILDDATE" >> $GITHUB_ENV
+    - name: Push neurodesk to Github packages (if changes found)
       if: env.GITHUB_REF != 'refs/heads/master' && env.ROOTFS_NEW != env.ROOTFS_CACHE
       run: |
         # Push to GH Packages
@@ -65,7 +64,45 @@ jobs:
         docker tag $IMAGEID:$SHORT_SHA $IMAGEID:latest
         docker push $IMAGEID:latest
         docker push $IMAGEID:$BUILDDATE
-    - name: Push to Dockerhub  (if enabled & changes found)
+    - name: Push neurodesk to Dockerhub  (if enabled & changes found)
+      if: env.GITHUB_REF != 'refs/heads/master' && env.DOCKERHUB_ORG != ''
+      run: |
+        # Push to GH Packages
+        docker tag $IMAGEID:$SHORT_SHA $DOCKERHUB_ORG/neurodesk:$BUILDDATE
+        docker tag $IMAGEID:$SHORT_SHA $DOCKERHUB_ORG/neurodesk:latest
+        docker push $DOCKERHUB_ORG/neurodesk:latest
+        docker push $DOCKERHUB_ORG/neurodesk:$BUILDDATE
+    - name: Pull latest VNM build from Github Packages
+      run: |
+        IMAGEID=docker.pkg.github.com/$GITHUB_REPOSITORY/vnm
+        IMAGEID=$(echo $IMAGEID | tr '[A-Z]' '[a-z]')
+        {
+          docker pull $IMAGEID \
+            && ROOTFS_CACHE=$(docker inspect --format='{{.RootFS}}' $IMAGEID) \
+            && echo "ROOTFS_CACHE=$ROOTFS_CACHE" >> $GITHUB_ENV
+        } || echo "$IMAGEID not found. Resuming build..."
+        echo "IMAGEID=$IMAGEID" >> $GITHUB_ENV
+    - name: Build new vnm image
+      run: |
+        SHORT_SHA=$(git rev-parse --short $GITHUB_SHA)
+        docker build . --file vnm/Dockerfile --tag $IMAGEID:$SHORT_SHA --cache-from $IMAGEID --label "GITHUB_REPOSITORY=$GITHUB_REPOSITORY" --label "GITHUB_SHA=$GITHUB_SHA"
+        ROOTFS_NEW=$(docker inspect --format='{{.RootFS}}' $IMAGEID:$SHORT_SHA)
+        BUILDDATE=`date +%Y%m%d`
+        echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
+        echo "ROOTFS_NEW=$ROOTFS_NEW" >> $GITHUB_ENV
+        echo "BUILDDATE=$BUILDDATE" >> $GITHUB_ENV
+    - name: Test VNM container image
+      run: |
+        /bin/bash .github/workflows/test_neurodesk_image.sh
+    - name: Push vnm to Github packages (if changes found)
+      if: env.GITHUB_REF != 'refs/heads/master' && env.ROOTFS_NEW != env.ROOTFS_CACHE
+      run: |
+        # Push to GH Packages
+        docker tag $IMAGEID:$SHORT_SHA $IMAGEID:$BUILDDATE
+        docker tag $IMAGEID:$SHORT_SHA $IMAGEID:latest
+        docker push $IMAGEID:latest
+        docker push $IMAGEID:$BUILDDATE
+    - name: Push vnm to Dockerhub  (if enabled & changes found)
       if: env.GITHUB_REF != 'refs/heads/master' && env.DOCKERHUB_ORG != ''
       run: |
         # Push to GH Packages
