made jobs dependent on each other

diff --git a/.github/workflows/neurodesk.yml b/.github/workflows/neurodesk.yml
--- a/.github/workflows/neurodesk.yml
+++ b/.github/workflows/neurodesk.yml
@@ -18,7 +18,92 @@ env:
   OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.SWIFT_OS_APPLICATION_CREDENTIAL_SECRET }}
 
 jobs:
-  build:
+  upload_containers_oracle:
+    runs-on: ubuntu-18.04
+    steps:
+    - uses: actions/checkout@v2
+    - uses: actions/setup-python@v2
+      with:
+        python-version: 3.8
+    - name: login to docker hubs
+      run: |
+        echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
+        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
+    - name : Check if singularity cache files exist in oracle cloud and swift storage and build if not there
+      run: |
+        echo ${GITHUB_REF}
+        echo "ORACLE_USER=$ORACLE_USER" >> $GITHUB_ENV 
+        echo "ORACLE_NEURODESK_BUCKET=$ORACLE_NEURODESK_BUCKET" >> $GITHUB_ENV 
+        /bin/bash .github/workflows/upload_containers_oracle.sh
+  test_neurodesk_cli:
+    runs-on: ubuntu-18.04
+    steps:
+    - uses: actions/checkout@v2
+    - uses: actions/setup-python@v2
+      with:
+        python-version: 3.8
+    - name: Test neurodesk cli version
+      run: |
+        /bin/bash .github/workflows/test_neurodesk_cli.sh
+  test_neurodesk_image:
+    runs-on: ubuntu-18.04
+    steps:
+    - uses: actions/checkout@v2
+    - uses: actions/setup-python@v2
+      with:
+        python-version: 3.8
+      - name: Test VNM container image
+      run: |
+        /bin/bash .github/workflows/test_neurodesk_image.sh
+  build_vnm:
+    needs: [upload_containers_oracle, test_neurodesk_cli, test_neurodesk_image]
+    runs-on: ubuntu-18.04
+    steps:
+    - uses: actions/checkout@v2
+    - uses: actions/setup-python@v2
+      with:
+        python-version: 3.8
+    - name: login to docker hubs
+      run: |
+        echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
+        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
+    - name: Pull latest vnm build from Github Packages
+      run: |
+        IMAGEID=docker.pkg.github.com/$GITHUB_REPOSITORY/vnm2
+        IMAGEID=$(echo $IMAGEID | tr '[A-Z]' '[a-z]')
+        {
+          docker pull $IMAGEID \
+            && ROOTFS_CACHE=$(docker inspect --format='{{.RootFS}}' $IMAGEID) \
+            && echo "ROOTFS_CACHE=$ROOTFS_CACHE" >> $GITHUB_ENV
+        } || echo "$IMAGEID not found. Resuming build..."
+        echo "IMAGEID=$IMAGEID" >> $GITHUB_ENV
+    - name: Build new vnm image
+      run: |
+        SHORT_SHA=$(git rev-parse --short $GITHUB_SHA)
+        docker build . --file vnm/Dockerfile --tag $IMAGEID:$SHORT_SHA --cache-from $IMAGEID --label "GITHUB_REPOSITORY=$GITHUB_REPOSITORY" --label "GITHUB_SHA=$GITHUB_SHA"
+        ROOTFS_NEW=$(docker inspect --format='{{.RootFS}}' $IMAGEID:$SHORT_SHA)
+        BUILDDATE=`date +%Y%m%d`
+        echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
+        echo "ROOTFS_NEW=$ROOTFS_NEW" >> $GITHUB_ENV
+        echo "BUILDDATE=$BUILDDATE" >> $GITHUB_ENV
+    - name: Push vnm to Github packages (if changes found)
+      if: env.GITHUB_REF != 'refs/heads/master' && env.ROOTFS_NEW != env.ROOTFS_CACHE
+      run: |
+        # Push to GH Packages
+        docker tag $IMAGEID:$SHORT_SHA $IMAGEID:$BUILDDATE
+        docker tag $IMAGEID:$SHORT_SHA $IMAGEID:latest
+        docker push $IMAGEID:latest
+        docker push $IMAGEID:$BUILDDATE
+    - name: Push vnm to Dockerhub  (if enabled & changes found)
+      if: env.GITHUB_REF != 'refs/heads/master' && env.DOCKERHUB_ORG != ''
+      run: |
+        # Push to GH Packages
+        docker tag $IMAGEID:$SHORT_SHA $DOCKERHUB_ORG/vnm:$BUILDDATE
+        docker tag $IMAGEID:$SHORT_SHA $DOCKERHUB_ORG/vnm:latest
+        docker push $DOCKERHUB_ORG/vnm:latest
+        docker push $DOCKERHUB_ORG/vnm:$BUILDDATE
+  build_neurodesk:
+    needs: [upload_containers_oracle, test_neurodesk_cli]
     runs-on: ubuntu-18.04
     steps:
     - uses: actions/checkout@v2
@@ -48,9 +133,6 @@ jobs:
         echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
         echo "ROOTFS_NEW=$ROOTFS_NEW" >> $GITHUB_ENV
         echo "BUILDDATE=$BUILDDATE" >> $GITHUB_ENV
-    - name: Test neurodesk cli version
-      run: |
-        /bin/bash .github/workflows/test_neurodesk_cli.sh
     - name: Push neurodesk to Github packages (if changes found)
       if: env.GITHUB_REF != 'refs/heads/master' && env.ROOTFS_NEW != env.ROOTFS_CACHE
       run: |
